### ISSUE TITLE
Can't parse space delimiters in page views count

### ISSUE THREAD

**Issue by dkoziy** [browserslist/browserslist-ga-export#14]
Hi, thanks for such beautiful tool! I've created perfect browserslist-stats.json for my project thanks to this repo.

But at first I recieved only zeros in output file, and as was mentioned in that issue the problem is in space delimiters:
https://github.com/browserslist/browserslist-ga/issues/35#issue-579799504
Unfortunately, google analytics exports in csv with space delimiters in pageviews if count is more than 1000.

I will send PR with the fix, please take a look at it.

**Comment by galvarez421** [comment]
Hi @dkoziy, thank you for the feedback! I'm glad to hear that this tool has been helpful to you.

That is an interesting finding -- I'm surprised the issue has not surfaced before! Given that the row arrays constructed in `index.js` are passed to the `parse` method exported by browserslist-ga, I think my preference would be to wait to see if this is something that browserslist-ga should account for, in which case we can wait to inherit the fix when browserslist-ga fixes the issue. However, it's possible that the issue exists only when using this tool (https://github.com/browserslist/browserslist-ga/issues/35 mentions CSV, which makes me wonder if that user is actually using this tool), as is presumably the case with the issue of commas in pageviews strings, in which case I think the fix in your PR would be a great fix.

Out of curiosity, when you export a CSV report in which a row has over 1000 pageviews, are space delimiters used in all cases? Are comma delimiters ever used? May I ask what user language setting you are using in Analytics? I just exported a custom report CSV and I see comma delimiters, so I'm wondering if the delimiter varies by user settings or some other settings.

**Comment by galvarez421** [comment]
Thank you for the feedback and information. I'm starting to think that it will make most sense for me to update the README so that the first usage step is to set user language setting to "English (United States)". I don't think it's feasible at this point to support an indefinite number of languages and the corresponding differences that may result from those language differences. Also, I think having users of this tool change that setting would be easier for the maintenance of the tool as well as for users (the latter due to simpler documentation). This certainly isn't the first time that a difference in language settings has resulted in the tool or its usage not working as expected (see https://github.com/browserslist/browserslist-ga-export/pull/5). What do you think?
