### ISSUE TITLE
ios_saf usage is incorrectly set to 0

### ISSUE THREAD

**Issue by kevinfarrugia** [browserslist/browserslist-ga-export#19]
I am creating a browserslist-stats.json file using `npx browserslist-ga-export --reportPath 'Users.txt'`, however the data in the output file does not match the data in the CSV file extracted from Google Analytics. The total usage also does not add up to 100%.

Input: [Users.txt](https://github.com/browserslist/browserslist-ga-export/files/6263453/Users.txt)

In the input file, you would notice three rows for iOS Safari (two are marked "In App" as they refer to native app web views) yet in the output JSON file you would see that ios_saf is 0 for all versions.

```
  "ios_saf": {
    "8": 0,
    "3.2": 0,
    "4.0-4.1": 0,
    "4.2-4.3": 0,
    "5.0-5.1": 0,
    "6.0-6.1": 0,
    "7.0-7.1": 0,
    "8.1-8.4": 0,
    "9.0-9.2": 0,
    "9.3": 0,
    "10.0-10.2": 0,
    "10.3": 0,
    "11.0-11.2": 0,
    "11.3-11.4": 0,
    "12.0-12.1": 0,
    "12.2-12.4": 0,
    "13.0-13.1": 0,
    "13.2": 0,
    "13.3": 0,
    "13.4-13.7": 0,
    "14.0-14.5": 0
  },
```

**Comment by galvarez421** [comment]
Hello, thank you for the report!

This appears to be due to the upstream issue https://github.com/browserslist/browserslist-ga/issues/37. Given that the goal of this package is still "to generate the same Browserslist custom usage data file that Browserslist-GA would generate", I think it would be appropriate to wait until the upstream package is fixed and to then inherit that fix.

I will leave this issue open for a bit in case you think there is a separate cause to this issue or have any other feedback.

**Comment by gc7g** [comment]
I'm also getting all zeros.
