### ISSUE TITLE
How to export data from GA4?

### ISSUE THREAD

**Issue by anantakrishna** [browserslist/browserslist-ga-export#20]
How to export data from [Google Analytics 4 property](https://support.google.com/analytics/answer/10089681)?

**Comment by galvarez421** [comment]
Hi, thank you for your question!

Having looked into this just a little bit, I'm not sure if Google Analytics 4 supports the same custom reports as previous versions (for example, see https://support.google.com/analytics/thread/111327086/creating-custom-reports-in-ga4?hl=en). Perhaps more importantly, however, is whether browserslist-ga supports GA 4 and if so, in what way. For example, perhaps GA 4 collects and/or reports the metrics and dimensions used by browserslist-ga and this tool in some different way. If that were the case, I think that this tool would aim to follow the lead of browserslist-ga as to how to parse that data, given the stated goal of this tool ("to generate the same Browserslist custom usage data file that Browserslist-GA would generate for a Google Analytics view"). It is also possible that, even if browserslist-ga supports GA 4, that it might not be possible for this tool to do so (for example, if there is no way to export a compatible custom report). If browserslist-ga does _not_ support GA 4, I'm not necessarily against having this tool support it, although it would probably be noted in the README that that usage of the tool deviates from equivalent functionality in browserslist-ga.

If anyone knows whether browserslist-ga supports GA 4 or whether GA 4 supports creating and exporting a custom report as described in this tool's README, please let us know! Otherwise, I will add this to my list of things to look into.

**Comment by anantakrishna** [comment]
Some research results.

- It is possible to export the same dimensions/metric using the GA4 [free-form exploration](https://support.google.com/analytics/answer/9327972).
- Browser version dimension is not available in the GA4 reports or API yet, only in the exploration workspace. Confirmed by the Google Analytics Team: https://stackoverflow.com/q/68256046/3082178.
- Downloaded CSV has some deviations from the format of UA custom report export:
   - Grand Total row goes after the headers row, therefore 8 rows should be skipped instead of 7.
   - Extra empty line in the end of the file which causes `TypeError: Cannot read property 'split' of undefined`.

After removing the last empty line from the file, `browserslist-ga-export` succeeded to ingest it and produce `browserslist-stats.json.

Sample of the downloaded CSV:

```csv
# ----------------------------------------
# property-name
# Free form-something
# 20210513-20210704
# ----------------------------------------

Operating system,OS version,Browser,Browser version,Device category,Event count
,,,,,2841,Grand total
iOS,14.4.2,Safari,14.0.3,mobile,253
Windows,10,Chrome,90.0.4430.212,desktop,155
Android,9,Chrome,90.0.4430.210,mobile,112
Android,10,Chrome,90.0.4430.210,mobile,96
iOS,14.6,Safari,14.1.1,mobile,90
```

Therefore, it seems to actions are needed to support GA4 here.
1. Add description into README on how to export data from GA4.
2. Fix issue with error caused by empty line in the end of the file.

**Comment by galvarez421** [comment]
Thank you so much for the detailed investigation and report -- very much appreciated! Great findings and summary of information.

I will not be able to look into this for at least a week, but I will start taking a look when I am able to. In the meanwhile, feel free to submit a pull request if you would like to (to develop branch). I'll have to give some thought to how to account for possibly increasing deviation between this tool and [browserslist-ga](https://github.com/browserslist/browserslist-ga). The premise of this tool is to provide a no-login alternative to browserslist-ga, but of course we could update the documentation to alter this premise so that this tool is not necessarily so closely coupled to browserslist-ga (e.g., if browserslist-ga does not yet or will not eventually support GA4).

Some initial thoughts based on your notes (not necessarily for anyone in particular to answer, just some things to consider when implementing changes):
- Perhaps it makes sense to add a CLI option to indicate which version of Analytics data is being used which will change how the report file is parsed, potentially including changing certain default CLI option values (e.g., `ignoreRows`)?
- Nice find on the empty line issue -- I assume that's probably an issue for UA reports right (i.e., not unique to GA4 reports)?

**Comment by pcrackenberg** [comment]
Just jumping into this, which seems relevant since UA is set to go away next month. It appears as though Browser Version comes through fine in a GA4 custom report, but OS version only is available in the "Operating system with version" option.

Here's an example from my report:
```
# ----------------------------------------
# property name
# Keep: OS/Browser-Free form 1
# 20230507-20230605
# ----------------------------------------

Operating system,Operating system with version,Browser,Browser version,Views
,,,,368478,Grand total
iOS,iOS 16.4.1,Safari,16.4,35095
Windows,Windows 10,Chrome,113.0.5672.127,30070
Windows,Windows 10,Chrome,113.0.5672.93,20588
iOS,iOS 16.3.1,Safari,16.3,12528
Windows,Windows 10,Chrome,112.0.5615.138,9646
Macintosh,Macintosh Intel 10.15,Safari,16.4,8203
iOS,iOS 16.1.1,Safari,16.1,7462
iOS,iOS 16.5,Safari,16.5,6273
iOS,iOS 16.2,Safari,16.2,5689
Windows,Windows 10,Edge,113.0.1774.35,4465
Windows,Windows 10,Edge,113.0.1774.42,4331
```

As a workaround it'd probably be easy to just drop the CSV in a spreadsheet and transform it, but that requires some extra work. Since GA4 includes OS and version together, maybe it'd just be easier to have the script take those in as a single column?

**Comment by TJ09** [comment]
> Just jumping into this, which seems relevant since UA is set to go away next month. It appears as though Browser Version comes through fine in a GA4 custom report, but OS version only is available in the "Operating system with version" option.

GA4 actually has "OS Version" as a dimension in addition to the combined "Operating system with version" dimension.

I was able to get browserslist-ga-export working with minimal changes to the CSV:

* I removed the "Grand total" line since it skewed the stats.
* I removed an extra blank line at the end of the file (the CSV ended with two newlines) that was causing a crash.

**Comment by galvarez421** [comment]
Thank you for the information! I am going to try to update this tool to accommodate GA4 soon; I just need to source some sample data and make sure I understand all of the relevant changes. Please feel free to make a pull request if you feel confident about the necessary changes.

**Comment by pcrackenberg** [comment]
> GA4 actually has "OS Version" as a dimension in addition to the combined "Operating system with version" dimension.

Hunh, you're right, it definitely didn't when I put the comment in, I guess Google must have added it in since then. Doing the changes you listed here worked great for me, thanks!

**Comment by galvarez421** [comment]
Google Analytics 4 is now supported as of [v5.0.0](https://github.com/browserslist/browserslist-ga-export/releases/tag/v5.0.0). Please try it out and let me know if you run into any issues! Thank you for all of the useful information provided in the comments above 😃.

**Comment by pcrackenberg** [comment]
Just downloaded a report from GA4, made no changes to it, and it worked great on v5.0.0. Thanks for the fix @galvarez421!
